### ISSUE TITLE
What license is this codebase under?

### ISSUE THREAD

**Issue by pulkitvyas08** [LoicGoyet/the-weel#1]
Hi @LoicGoyet thanks for the fantastic work you have done with this repository. Since there is no license file or related information in `package.json`, I wondered how you have licensed your code. I am building a project and wanted to know if it would be cool with you if I modified your code to my requirements and used it for commercial purposes

**Comment by LoicGoyet** [comment]
Oh yeah don't worry you can reuse the code, I'm fine with that. You can fork it and change it the way you want it.

Just be aware that this code is not production ready for me. On Safari, the paint rendering is buggy. Also on production, I'd rather use canvas for this kind of UI, DOM rendering methods are not designed to do that, so it could have performance or rendering issues depending on the clients.

But if it fits your requirements, go ahead

**Comment by pulkitvyas08** [comment]
Awesome, thanks!
